config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root 'home#index'

  devise_for :admins, :controllers => { :sessions => "admin/sessions" }

  resources :home, only: [:index]
  resources :services, only: [:index]
  resources :contacts, only: [:index, :create]
  resources :feedbacks, only: [:index, :create]
  resources :studio, only: [:index]

  namespace :portfolio do
    resources :newborns, only: [:index, :show]
    resources :kids, only: [:index, :show]
    resources :pregnancy, only: [:index, :show]
    resources :families, only: [:index, :show]
  end

  namespace :admin do
    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end

    resources :home, only: [:index]
    resources :slides
    resources :services
    resources :albums do
      resources :photos do
        get 'make_as_album_cover', to: 'photos#make_as_album_cover'
      end
    end
    resources :pages
    resources :instagram, only: [:index]
    resources :feedbacks do
      get 'publish', to: 'feedbacks#publish'
    end

    get 'published_feedbacks', to: 'feedbacks#published_feedbacks'

    get 'instagram/callback' => 'instagram#callback'
    get 'instagram/update_photos_manually' => 'instagram#update_photos_manually'

  end

  get :admin, to: 'admin/home#index'

  # redirect to root on 404s
  get "*path" => redirect("/")

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :photos, dependent: :destroy

  validates :display_as, presence: true
  validates :name, presence: true

  enum category: Option.get_options('categories')
  enum display_as: Option.get_options('display_as')

  accepts_nested_attributes_for :photos, allow_destroy: true

  scope :pregnancy_albums, -> { includes(:photos).where(category: 0, display: true ).where.not(photos: {id: nil}).order(id: :asc) }
  scope :newborn_albums, -> { includes(:photos).where(category: 1, display: true ).where.not(photos: {id: nil}).order(id: :asc) }
  scope :kid_albums, -> { includes(:photos).where(category: 2, display: true ).where.not(photos: {id: nil}).order(id: :asc) }
  scope :family_albums, -> { includes(:photos).where(category: 3, display: true).where.not(photos: {id: nil}).order(id: :asc) }

  scope :photo_book_albums, -> { includes(:photos).where(category: 4, display: true ).where.not(photos: {id: nil}).order(id: :asc) }
  scope :studio_albums, -> { includes(:photos).where(category: 5, display: true ).where.not(photos: {id: nil}).order(id: :asc) }

  scope :albums_as_album, -> { where(display_as: 0) }
  scope :albums_as_carousel, -> { where(display_as: 1) }

  def cover
    photos.where(album_cover: true).first
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_form.rb
class ContactForm < MailForm::Base

  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :service,   :validate => true
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "#{service}",
      :to => ENV['google_account_login'],
      :from => %("#{name}" <#{email}>)
    }
  end

end

app/models/feedback.rb
class Feedback < ApplicationRecord
  has_many :photos, dependent: :destroy

  accepts_nested_attributes_for :photos, allow_destroy: true

  validates :customer_name, presence: true
  validates :body, presence: true

  scope :published, -> { where(published: true) }

  def publish!
    self.update_attributes(published: true) unless published
  end


end

app/models/instagram_photo.rb
class InstagramPhoto < ApplicationRecord

  def self.get_last_photos
    if self.count == 0
      InstagramCollectorWorker.perform_async
      self.last(10).reverse
    elsif self.last.present? && self.last.created_at < 1.hour.ago
      InstagramCollectorWorker.perform_async
      self.last(10).reverse
    else
      self.last(10).reverse
    end
  end

end

app/models/option.rb
class Option < ApplicationRecord

  OPTIONS = {

    yes_or_no: {
      'Да' => true,
      'Нет' => false
    },

    categories: {
      'Беременность' => 0,
      'Новорожденные' => 1,
      'Дети до года' => 2,
      'Семьи' => 3,
      'Фотокниги' => 4,
      'Mimi studio' => 5
    },

    service_categories: {
      'Беременность' => 0,
      'Новорожденные' => 1,
      'Семьи' => 2
    },

    display_as: {
      'Альбом' => 0,
      'Карусель' => 1
    },

    slide_positions: {
      'Домашняя страница' => 0
    },

    pages: {
      'Новорожденные' => 0,
      'Семьи' => 1,
      'Дети до года' => 2,
      'Беременность' => 3,
      'Домашняя страница' => 4,
      'Услуги' => 5,
      'Контакты' => 6,
      'Отзывы' => 7,
      'Mimi studio' => 8
    }

  }

  def self.get_options(type)
    self::OPTIONS[type.to_sym]
  end

end

app/models/page.rb
class Page < ApplicationRecord
  mount_uploader :header_image, PagesUploader

  validates :name, uniqueness: true

  enum name: Option.get_options('pages')

  scope :newborns_page,  -> { where(name: 0).first }
  scope :families_page,  -> { where(name: 1).first }
  scope :kids_page,      -> { where(name: 2).first }
  scope :pregnancy_page, -> { where(name: 3).first }
  scope :home_page,      -> { where(name: 4).first }
  scope :services_page,  -> { where(name: 5).first }
  scope :contacts_page,  -> { where(name: 6).first }
  scope :feedbacks_page, -> { where(name: 7).first }
  scope :studio_page,    -> { where(name: 8).first }

end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, PhotoUploader

  belongs_to :album, optional: true
  belongs_to :feedback, optional: true

  scope :feedback_photos, -> { where.not(feedback_id: nil) }

  def make_as_album_cover
    unless album_cover
      Album.find(album_id).photos.update_all(album_cover: false)
      self.update_attributes(album_cover: true)
    end
  end

end

app/models/service.rb
class Service < ApplicationRecord

  enum category: Option.get_options('service_categories')

  validates :name, presence: true
  validates :category, presence: true
  validates :description, presence: true

  scope :pregnancy_services, -> { where(category: 0) }
  scope :newborn_services, -> { where(category: 1) }
  scope :family_services, -> { where(category: 2) }

end

app/models/slide.rb
class Slide < ApplicationRecord
  mount_uploader :image, SlideUploader

  enum position: Option.get_options('slide_positions')

  scope :homepage_slides, -> { where(position: 0) }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ActsAsTaggable

  before_action :set_page
  before_action -> { set_page_meta_tags(@page) }

  def index
    @slides = Slide.homepage_slides.order(created_at: :asc)
    @instagram_photos = InstagramPhoto.get_last_photos

    @newborns_gallery_photo = Album.newborn_albums.last.try(:cover)
    @pregnancy_gallery_photo = Album.pregnancy_albums.last.try(:cover)
    @kids_gallery_photo = Album.kid_albums.last.try(:cover)
    @families_gallery_photo = Album.family_albums.first.try(:cover)

    newborn_services = Service.newborn_services.order(:position)
    family_services = Service.family_services.order(:position)
    pregnancy_services = Service.pregnancy_services.order(:position)

    @all_services = [
                      pregnancy_services,
                      newborn_services,
                      family_services
                    ]
  end

  private

  def set_page
    @page = Page.home_page
  end

end

app/controllers/studio_controller.rb
class StudioController < ApplicationController
  include ActsAsTaggable

  before_action :set_page
  before_action -> { set_page_meta_tags(@page) }

  def index
    @album = Album.albums_as_carousel.studio_albums
  end

  private

  def set_page
    @page = Page.studio_page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/studio_helper.rb
module StudioHelper
end

app/views/admin/pages/edit.html.erb
<%= render partial: 'admin_partials/page_heading', locals: { heading: "Редактировать страницу" } %>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Редактировать страницу (<%= @page.name %>)
      </div>
      <div class="panel-body">
        <%= form_for [:admin, @page] do |f| %>
          <div class="row">
            <div class="col-lg-6">

              <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label :description %>
                <%= f.text_field :description, class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label :keywords %>
                <%= f.text_field :keywords, class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label 'Изображение в шапке' %>
                <%= f.file_field :header_image %>
              </div>

              <div class="form-group">
                <%= f.label 'Текст в шапке' %>
                <%= f.text_field :header_text, class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label 'Оглавление страницы 1' %>
                <%= f.text_field :page_content_heading_1, class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label 'Содержание страницы 1' %>
                <%= f.trix_editor :page_content_body_1 %>
              </div>

              <div class="form-group">
                <%= f.label 'Оглавление страницы 2' %>
                <%= f.text_field :page_content_heading_2, class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label 'Содержание страницы 2' %>
                <%= f.trix_editor :page_content_body_2 %>
              </div>

              <div class="form-group">
                <%= f.label 'Оглавление страницы 3' %>
                <%= f.text_field :page_content_heading_3, class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label 'Содержание страницы 3' %>
                <%= f.trix_editor :page_content_body_3 %>
              </div>

            </div>

            <% if @page.name == 'Контакты' %>

              <div class="col-lg-6">

                <h4> Ссылки </h4>

                <hr>

                <div class="form-group">
                  <%= f.label 'Телефон' %>
                  <%= f.text_field :phone_number, class: 'form-control' %>
                </div>

                <div class="form-group">
                  <%= f.label 'Адрес' %>
                  <%= f.text_field :address, class: 'form-control' %>
                </div>

                <div class="form-group">
                  <%= f.label :email %>
                  <%= f.text_field :email, class: 'form-control' %>
                </div>

                <div class="form-group">
                  <%= f.label 'Facebook' %>
                  <%= f.text_field :facebook_url, class: 'form-control' %>
                </div>

                <div class="form-group">
                  <%= f.label 'Instagram' %>
                  <%= f.text_field :instagram_url, class: 'form-control' %>
                </div>

                <div class="form-group">
                  <%= f.label 'VK' %>
                  <%= f.text_field :vk_url, class: 'form-control' %>
                </div>

              </div>

            <% end %>

          </div>

          <%= f.submit 'Сохранить', class: 'btn btn-success' %>

          <%= link_to 'Назад', admin_pages_path, class: 'btn btn-default' %>

        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/admin/pages/index.html.erb
<%= render partial: 'admin_partials/page_heading', locals: { heading: "Страницы" } %>

<% if @pages.present? %>

    <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          Страницы
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
          <table width="100%" class="table table-striped table-bordered table-hover" id="dataTable">
            <thead>
              <tr>
                <th>Страница</th>
                <th>Действия</th>
              </tr>
            </thead>
            <tbody>
              <% @pages.each do |page| %>
                <tr class="odd gradeX">

                  <td><%= page.name %></td>

                  <td style="width: 5%">
                    <div class="row">

                      <div class="col-lg-12 text-center">
                        <%= link_to edit_admin_page_path(page) do %>
                          <%= fa_icon 'pencil' %>
                        <% end %>
                      </div>

                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <!-- /.table-responsive -->
        </div>
          <!-- /.panel-body -->
      </div>
      <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
  </div>

<% end %>

app/views/admin_partials/_navbar_header.html.erb
<div class="navbar-header">

  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>

  <%= link_to admin_home_index_path, class: 'navbar-brand' do %>
    Admin Panel
  <% end %>

</div>

<ul class="nav navbar-top-links navbar-right">
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-user">
      <li>
        <%= link_to destroy_admin_session_path, method: :delete do %>
          Выход
        <% end %>
      </li>
    </ul>
  </li>
</ul>

app/views/admin_partials/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <%= render 'admin_partials/navbar_header' %>
  <%= render 'admin_partials/side_bar' %>
</nav>

app/views/admin_partials/_page_heading.html.erb
<div class="row">
  <div class="col-lg-6">
    <h4><%= heading %></h4>
  </div>
</div>

<hr>

app/views/admin_partials/_side_bar.html.erb
<div class="navbar-default sidebar" role="navigation">
   <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">

        <li>
         <%= link_to admin_albums_path do %>
           <%= fa_icon 'folder-o' %> Альбомы
         <% end %>
        </li>

        <li>
         <%= link_to admin_slides_path do %>
           <%= fa_icon 'picture-o' %> Слайдеры
         <% end %>
        </li>

        <li>
         <%= link_to admin_pages_path do %>
           <%= fa_icon 'align-left' %> Страницы
         <% end %>
        </li>

        <li>
         <%= link_to admin_services_path do %>
           <%= fa_icon 'align-left' %> Пакеты услуг
         <% end %>
        </li>

        <li>
         <%= link_to admin_feedbacks_path do %>
           <%= fa_icon 'comments' %> Отзывы
           <% if Feedback.where(published: false).present? %>
             <%= fa_icon 'exclamation', style: 'color: red' %>
           <% end %>
         <% end %>
        </li>

        <li>
         <%= link_to admin_instagram_index_path do %>
           <%= fa_icon 'instagram' %> Instagram
         <% end %>
        </li>

      </ul>
   </div>
</div>