config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root 'home#index'

  devise_for :admins, :controllers => { :sessions => "admin/sessions" }

  resources :home, only: [:index]
  resources :services, only: [:index]
  resources :contacts, only: [:index, :create]
  resources :feedbacks, only: [:index, :create]
  resources :studio, only: [:index]

  namespace :portfolio do
    resources :newborns, only: [:index, :show]
    resources :kids, only: [:index, :show]
    resources :pregnancy, only: [:index, :show]
    resources :families, only: [:index, :show]
  end

  namespace :admin do
    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end

    resources :home, only: [:index]
    resources :slides
    resources :services
    resources :albums do
      resources :photos do
        get 'make_as_album_cover', to: 'photos#make_as_album_cover'
      end
    end
    resources :pages
    resources :instagram, only: [:index]
    resources :feedbacks do
      get 'publish', to: 'feedbacks#publish'
    end

    get 'published_feedbacks', to: 'feedbacks#published_feedbacks'

    get 'instagram/callback' => 'instagram#callback'
    get 'instagram/update_photos_manually' => 'instagram#update_photos_manually'

  end

  get :admin, to: 'admin/home#index'

  # redirect to root on 404s
  get "*path" => redirect("/")

end

app/models/service.rb
class Service < ApplicationRecord

  enum category: Option.get_options('service_categories')

  validates :name, presence: true
  validates :category, presence: true
  validates :description, presence: true

  scope :pregnancy_services, -> { where(category: 0) }
  scope :newborn_services, -> { where(category: 1) }
  scope :family_services, -> { where(category: 2) }

end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < Admin::BaseController

  before_action :find_service, only: [:show, :edit, :update, :edit, :destroy]

  def index
    @services = Service.all.order(:category)
  end

  def show
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new service_params
    if @service.save
      redirect_to admin_services_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @service.update_attributes service_params
      redirect_to admin_services_path
    else
      render :edit
    end
  end

  def destroy
    if @service.destroy
      redirect_to admin_services_path
    end
  end

  private

  def find_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:name, :description, :position, :category, :price)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  include ActsAsTaggable

  before_action :set_page
  before_action -> { set_page_meta_tags(@page) }


  def index
    @carousels = Album.albums_as_carousel.photo_book_albums

    newborn_services = Service.newborn_services.order(:position)
    family_services = Service.family_services.order(:position)
    pregnancy_services = Service.pregnancy_services.order(:position)

    @all_services = [
                      pregnancy_services,
                      newborn_services,
                      family_services
                    ]
  end

  private

  def set_page
    @page = Page.services_page
  end
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/admin/services/_form.html.erb
<div class="form-group">
  <%= f.label 'Категория' %>
  <%= f.select(:category, Service.categories.keys.to_a, {include_blank: 'Выбрать категорию...'}, { :class => 'form-control' }) %>
</div>

<div class="form-group">
  <%= f.label 'Имя' %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label 'Цена' %>
  <%= f.text_field :price, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label 'Описание' %>
  <%= f.trix_editor :description %>
</div>

<div class="form-group">
  <%= f.label 'Позиция' %>
  <%= f.select(:position, [1,2,3,4], {include_blank: 'Выбрать позицию...'}, { :class => 'form-control' }) %>
</div>

app/views/admin/services/edit.html.erb
<%= render partial: 'admin_partials/page_heading', locals: { heading: 'Редактировать пакет услуг' } %>

<div class="row">
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        Редактировать пакет услуг
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12">
            <%= form_for [:admin, @service] do |f| %>

              <%= render partial: 'form', locals: { f: f } %>

              <%= f.submit 'Сохранить', class: 'btn btn-success' %>

              <%= link_to 'Назад', admin_services_path, class: 'btn btn-default' %>

            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/services/index.html.erb
<div class="row">
  <div class="col-lg-6">
    <h4>Пакеты услуг</h4>
  </div>
  <div class="col-lg-6">
    <%= link_to 'Добавить пакет услуг', new_admin_service_path, class: 'btn btn-success pull-right new-record-button' %>
  </div>
</div>

<hr>

<% if @services.present? %>

    <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          Пакеты услуг
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
          <table width="100%" class="table table-striped table-bordered table-hover" id="dataTable">
            <thead>
              <tr>
                <th>Название пакета</th>
                <th>Категория</th>
                <th>Позиция</th>
                <th>Действия</th>
              </tr>
            </thead>
            <tbody>
              <% @services.each do |service| %>
                <tr class="odd gradeX">

                  <td><%= service.name %></td>
                  <td><%= service.category %></td>
                  <td><%= service.position %></td>

                  <td style="width: 5%">
                    <div class="row">

                      <div class="col-lg-6 text-center">
                        <%= link_to edit_admin_service_path(service) do %>
                          <%= fa_icon 'pencil' %>
                        <% end %>
                      </div>

                      <div class="col-lg-6 text-center">
                        <%= link_to admin_service_path(service), method: :delete, data: { confirm: 'Are you sure?' } do %>
                          <%= fa_icon 'trash' %>
                      <% end %>

                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <!-- /.table-responsive -->
        </div>
          <!-- /.panel-body -->
      </div>
      <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
  </div>

<% end %>

app/views/admin/services/new.html.erb
<%= render partial: 'admin_partials/page_heading', locals: { heading: 'Новый пакет услуг' } %>

<div class="row">
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        Новый пакет услуг
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12">
            <%= form_for [:admin, @service] do |f| %>

              <%= render partial: 'form', locals: { f: f } %>

              <%= f.submit 'Сохранить', class: 'btn btn-success' %>

              <%= link_to 'Назад', admin_services_path, class: 'btn btn-default' %>

            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>