config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root 'home#index'

  devise_for :admins, :controllers => { :sessions => "admin/sessions" }

  resources :home, only: [:index]
  resources :services, only: [:index]
  resources :contacts, only: [:index, :create]
  resources :feedbacks, only: [:index, :create]
  resources :studio, only: [:index]

  namespace :portfolio do
    resources :newborns, only: [:index, :show]
    resources :kids, only: [:index, :show]
    resources :pregnancy, only: [:index, :show]
    resources :families, only: [:index, :show]
  end

  namespace :admin do
    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end

    resources :home, only: [:index]
    resources :slides
    resources :services
    resources :albums do
      resources :photos do
        get 'make_as_album_cover', to: 'photos#make_as_album_cover'
      end
    end
    resources :pages
    resources :instagram, only: [:index]
    resources :feedbacks do
      get 'publish', to: 'feedbacks#publish'
    end

    get 'published_feedbacks', to: 'feedbacks#published_feedbacks'

    get 'instagram/callback' => 'instagram#callback'
    get 'instagram/update_photos_manually' => 'instagram#update_photos_manually'

  end

  get :admin, to: 'admin/home#index'

  # redirect to root on 404s
  get "*path" => redirect("/")

end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, PhotoUploader

  belongs_to :album, optional: true
  belongs_to :feedback, optional: true

  scope :feedback_photos, -> { where.not(feedback_id: nil) }

  def make_as_album_cover
    unless album_cover
      Album.find(album_id).photos.update_all(album_cover: false)
      self.update_attributes(album_cover: true)
    end
  end

end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Admin::BaseController

  before_action :find_photo, only: [:destroy, :show, :edit, :update]

  def index
    @album = Album.find(params[:album_id])
    @photos = @album.photos
  end

  def show
  end

  def edit
  end

  def update
    if @photo.update_attributes photo_params
      redirect_to admin_album_photos_path(@photo.album)
    else
      render :edit
    end
  end

  def destroy
    if @photo.destroy
      redirect_to admin_album_photos_path(@photo.album)
    end
  end

  def make_as_album_cover
    photo = Photo.find(params[:photo_id])
    photo.make_as_album_cover
    respond_to do |format|
      format.js { render js: "window.location.pathname='#{admin_album_photos_path(photo.album)}'" }
    end
  end

  private

  def photo_params

    params.require(:photo).permit(:name, :alt, :title, :image)

  end

  def find_photo
    @photo = Photo.find params[:id]
  end

end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/views/admin/photos/_form.html.erb
<div class="form-group">
  <%= f.label 'Название' %>
  <%= f.text_field :name, :class => 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :alt %>
  <%= f.text_field :alt, :class => 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label 'Изображение' %>
  <%= f.file_field :image %>
</div>

app/views/admin/photos/edit.html.erb
<%= render partial: 'admin_partials/page_heading', locals: { heading: 'Редактировать фотографию' } %>

<div class="row">
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        Редактировать альбом
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12">
            <%= form_for [:admin, @photo.album, @photo], html: { multipart: true } do |f| %>

              <%= render partial: 'form', locals: { f: f } %>

              <%= f.submit 'Сохранить', class: 'btn btn-success' %>

              <%= link_to 'Назад', admin_albums_path, class: 'btn btn-default' %>

            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/photos/index.html.erb
<div class="row">
  <div class="col-lg-6">
    <h4>Фотографии (<%= @album.name %>)</h4>
  </div>
  <div class="col-lg-6">
    <%= link_to 'Добавить фотографии', edit_admin_album_path(@album), class: 'btn btn-success pull-right new-record-button' %>
  </div>
</div>

<hr>

<% if @photos.present? %>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          Фотографии (<%= @album.name %>)
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
          <table width="100%" class="table table-striped table-bordered table-hover" id="dataTable">
            <thead>
              <tr>
                <th>Название</th>
                <th>Alt</th>
                <th>Title</th>
                <th>Обложка альбома</th>
                <th>Фотография</th>
                <th>Действия</th>
              </tr>
            </thead>
            <tbody>
              <% @photos.each do |photo| %>
                <tr class="odd gradeX">

                  <td> <%= photo.name %> </td>

                  <td> <%= photo.alt %> </td>

                  <td> <%= photo.title %></td>
                  <% if photo.album_cover %>
                    <td> да </td>
                  <% else %>
                    <td> нет <%= link_to '(сделать обложкой)', admin_album_photo_make_as_album_cover_path(photo.album, photo), data: { id: photo.id, album_id: photo.album.id }, remote: true, class: 'make_as_album_cover' %> </td>
                  <% end %>

                  <td> <%= image_tag photo.image_url(:thumb) %> </td>

                  <td style="width: 5%">
                    <div class="row">

                      <div class="col-lg-6 text-center">
                        <%= link_to edit_admin_album_photo_path(photo.album, photo) do %>
                          <%= fa_icon 'pencil' %>
                        <% end %>
                      </div>

                      <div class="col-lg-6 text-center">
                        <%= link_to admin_album_photo_path(photo.album, photo), method: :delete, data: { confirm: 'Are you sure?' } do %>
                          <%= fa_icon 'trash' %>
                      <% end %>

                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <!-- /.table-responsive -->
        </div>
          <!-- /.panel-body -->
      </div>
      <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
<% end %>