config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root 'home#index'

  devise_for :admins, :controllers => { :sessions => "admin/sessions" }

  resources :home, only: [:index]
  resources :services, only: [:index]
  resources :contacts, only: [:index, :create]
  resources :feedbacks, only: [:index, :create]
  resources :studio, only: [:index]

  namespace :portfolio do
    resources :newborns, only: [:index, :show]
    resources :kids, only: [:index, :show]
    resources :pregnancy, only: [:index, :show]
    resources :families, only: [:index, :show]
  end

  namespace :admin do
    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end

    resources :home, only: [:index]
    resources :slides
    resources :services
    resources :albums do
      resources :photos do
        get 'make_as_album_cover', to: 'photos#make_as_album_cover'
      end
    end
    resources :pages
    resources :instagram, only: [:index]
    resources :feedbacks do
      get 'publish', to: 'feedbacks#publish'
    end

    get 'published_feedbacks', to: 'feedbacks#published_feedbacks'

    get 'instagram/callback' => 'instagram#callback'
    get 'instagram/update_photos_manually' => 'instagram#update_photos_manually'

  end

  get :admin, to: 'admin/home#index'

  # redirect to root on 404s
  get "*path" => redirect("/")

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ActsAsTaggable

  before_action :set_page
  before_action -> { set_page_meta_tags(@page) }

  def index
    @slides = Slide.homepage_slides.order(created_at: :asc)
    @instagram_photos = InstagramPhoto.get_last_photos

    @newborns_gallery_photo = Album.newborn_albums.last.try(:cover)
    @pregnancy_gallery_photo = Album.pregnancy_albums.last.try(:cover)
    @kids_gallery_photo = Album.kid_albums.last.try(:cover)
    @families_gallery_photo = Album.family_albums.first.try(:cover)

    newborn_services = Service.newborn_services.order(:position)
    family_services = Service.family_services.order(:position)
    pregnancy_services = Service.pregnancy_services.order(:position)

    @all_services = [
                      pregnancy_services,
                      newborn_services,
                      family_services
                    ]
  end

  private

  def set_page
    @page = Page.home_page
  end

end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= render 'front_partials/carousel' %>

<div class="container">
  <div class="content-area">

    <% if @page.page_content_heading_1.present? %>

      <h1 class="first-heading text-center"><%= @page.page_content_heading_1 %></h1>

    <% end %>

    <div class="row welcome-text">
      <div class="col-lg-4 col-md-4 col-sm-4">

        <%= image_tag 'avatar', class: 'avatar img-responsive', alt: 'фотограф новорожденных и детей до года Даша Катасонова', title: 'фотограф новорожденных и детей до года Даша Катасонова' %>

      </div>

      <div class="col-lg-8 col-md-8 col-sm-8">

        <%= @page.page_content_body_1.try(:html_safe) %>

      </div>
    </div>

    <hr>

    <div class="embeded-video-box">
      <iframe class="embeded-video" src="https://www.youtube.com/embed/Jcz1letVLfM"></iframe>
    </div>

    <hr>

    <!-- my works -->

    <% if @page.page_content_heading_2.present? %>

      <h2 class="section-heading"><%= @page.page_content_heading_2 %></h2>

    <% end %>

    <h2 class="section-heading">Мои работы</h2>

    <div class="my-galleries">
      <div class="row">

        <% if @newborns_gallery_photo.present? %>

          <div class="homepage-album col-lg-3 col-sm-3 col-xs-6 album-col">
            <%= link_to portfolio_pregnancy_index_path do %>
              <%= image_tag @pregnancy_gallery_photo.image_url(:album_cover), alt: 'Даша Катасонова фотосессии беременности Харьков.', height: '360px', width: '360px', class: 'img-responsive gallery-album' %>
              <div class="overlay">
                <div class="album-text text-center">Беременность</div>
              </div>
            <% end %>
          </div>

        <% end %>

        <% if @newborns_gallery_photo.present? %>

          <div class="homepage-album col-lg-3 col-sm-3 col-xs-6 album-col">
            <%= link_to portfolio_newborns_path do %>
              <%= image_tag @newborns_gallery_photo.image_url(:album_cover), alt: 'Даша Катасонова фотограф новорожденных, фотосессии новорожденных Харьков.', height: '360px', width: '360px', class: 'img-responsive gallery-album' %>
              <div class="overlay">
                <div class="album-text text-center">Новорожденные</div>
              </div>
            <% end %>
          </div>

        <% end %>

        <% if @kids_gallery_photo.present? %>

          <div class="homepage-album col-lg-3 col-sm-3 col-xs-6 album-col">
            <%= link_to portfolio_kids_path do %>
              <%= image_tag @kids_gallery_photo.image_url(:album_cover), alt: 'Даша Катасонова детские фотосессии, детский фотограф Харьков.', height: '360px', width: '360px', class: 'img-responsive gallery-album' %>
              <div class="overlay">
                <div class="album-text text-center">Дети до года</div>
              </div>
            <% end %>
          </div>

        <% end %>

        <% if @families_gallery_photo.present? %>

          <div class="homepage-album col-lg-3 col-sm-3 col-xs-6 album-col">
            <%= link_to portfolio_families_path do %>
              <%= image_tag @families_gallery_photo.image_url(:album_cover), height: '360px', width: '360px', alt: 'Даша Катасонова семейные фотосессии, семейный фотограф Харьков.', class: 'img-responsive gallery-album' %>
              <div class="overlay">
                <div class="album-text text-center">Семьи</div>
              </div>
            <% end %>
          </div>

        <% end %>

      </div>
    </div>

    <h2 class="text-center">Пакеты услуг</h2>

    <%= render partial: 'front_partials/services', locals: { all_services: @all_services } %>

    <% if @instagram_photos.present? %>

      <h2 class="section-heading">Я в Instagram</h2>

      <ul class="photostream">

        <% @instagram_photos.each do |photo| %>

          <li>
            <%= link_to photo.link, target: '_blank' do %>
              <%= image_tag photo.image_url, alt: 'Даша Катасонова детский и семейный фотограф Харьков, фотосессии новорожденных. Мой инстаграм', class: 'img-responsive' %>
            <% end %>
          </li>

        <% end %>

      </ul>

    <% end %>

  </div>
</div>